# This is a basic workflow to help you get started with Actions

name: Android Build CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Haxe
      - name: Install Haxe
        run: |
          # Download and install Haxe
          sudo apt-get update
          sudo apt-get install haxe -y
          haxe --version  # Verify Haxe installation
      
      # Upgrade Haxe to the latest version (4.2.4)
      - name: Upgrade Haxe
        run: haxelib install haxe 4.2.4
        
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %HAXELIB_ROOT%
          key: ${{ runner.os }}-android
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '11'
        
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r15c
      
      # Add the Update haxelib step
      - name: Update haxelib
        run: haxelib --global update haxelib

      # Install Lime
      - name: Install Lime
        run: haxelib install lime 7.9.0 --quiet

      # Verify Lime Installation
      - name: Verify Lime Installation
        run: haxelib list

      # Configure %HAXELIB_ROOT%
      - name: Configure %HAXELIB_ROOT%
        run: |
          mkdir -p "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          
      # Rest of your haxelib commands here

      - name: Build Log
        run: |
          haxelib run lime setup android
          haxelib run lime build android -Dci
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk/debug
